export type IssueInfo = {
  key: string;
  summary: string;
  status: string;
  type: string;
  created: string;
  resolved: string;
  resolution: string;
  epicKey: string | null;
  epicName: string | null;
  initiativeKey: string | null;
  initiativeName: string | null;
  labels: string[];
  priority: string;
  components: string[];
  fixVersions: string[];
  url: string;
  timeoriginalestimate: number | null;
  timespent: number | null;
};